name: Checks
on: [push, pull_request]
jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.1'
            - run: composer install --no-progress --prefer-dist
            - run: composer check
